require  "mappings.mappings"
require  "settings.settings"
require  "plugins.packer"
require  "plugins.plug-colorizer"
require  "plugins.treesitter"
require  "plugins.lualine"
require  "plugins.neo-tree"
